import { createElement } from '@lwc/engine-dom';
import Scenario1_DataBinding_DisplayUserDetails from 'c/scenario1_DataBinding_DisplayUserDetails';

describe('c-scenario1-data-binding-display-user-details', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scenario1-data-binding-display-user-details', {
            is: Scenario1_DataBinding_DisplayUserDetails
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});