import { createElement } from '@lwc/engine-dom';
import Scenario2_conditionalRendering from 'c/scenario2_conditionalRendering';

describe('c-scenario2-conditional-rendering', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scenario2-conditional-rendering', {
            is: Scenario2_conditionalRendering
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});