import { createElement } from '@lwc/engine-dom';
import Scenario10_taskIteration from 'c/scenario10_taskIteration';

describe('c-scenario10-task-iteration', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scenario10-task-iteration', {
            is: Scenario10_taskIteration
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});