import { createElement } from '@lwc/engine-dom';
import Scenario6_iterationBasic from 'c/scenario6_iterationBasic';

describe('c-scenario6-iteration-basic', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-scenario6-iteration-basic', {
            is: Scenario6_iterationBasic
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});